# wolfie (github.com/ToneAr/wolfie): Wolfram Language CLI/REPL.
#
#   wolfie.enable = true;          # in configuration.nix
#   wolfie.version = "v0.9.20b";   # optional pin; default "latest"
#
# Installed the way the README says, with the upstream bootstrap script:
#   curl -fsSL .../installers/install.sh | bash
# It downloads the prebuilt release binary into ~/.local/bin. That binary is
# linked against a normal glibc, so it runs through nix-ld; its libraries
# (libuuid, libstdc++, libgcc_s) are in nix-ld's default set.
#
# This is deliberately impure (network at install time, not a Nix build):
# it runs as a user oneshot service that retries every minute until it has
# network, so it also works on a first boot that comes up offline.
#   - not installed yet            -> install
#   - wolfie.version pinned & changed -> reinstall that tag (--force)
#   - "latest" and already installed  -> leave it; to upgrade run
#       systemctl --user restart wolfie-install  after deleting
#       ~/.local/state/wolfie/installed-version
#
# At runtime wolfie needs a Wolfram kernel: enable wolfram.nix, or have
# WolframKernel/wolframscript reachable on PATH.
{ config, lib, pkgs, username, ... }:
let
  cfg = config.wolfie;
  installerUrl = "https://raw.githubusercontent.com/ToneAr/wolfie/main/installers/install.sh";

  # What install.sh shells out to. getconf matters: it reports glibc 2.42,
  # which selects the linux-ubuntu24 build.
  installerPath = lib.makeBinPath (with pkgs; [
    bash curl gnutar gzip coreutils gawk gnused findutils getconf
  ]);

  install-wolfie = pkgs.writeShellScript "install-wolfie" ''
    set -eu
    bin_dir="$HOME/.local/bin"
    state="$HOME/.local/state/wolfie/installed-version"
    want=${lib.escapeShellArg cfg.version}

    if [ -x "$bin_dir/wolfie" ]; then
      if [ "$want" = latest ] || [ "$(cat "$state" 2>/dev/null)" = "$want" ]; then
        exit 0
      fi
    fi

    # install.sh edits ~/.bashrc / ~/.profile when the install dir is not on
    # PATH. It is already on PATH via home.sessionPath, so say so here too.
    export PATH="$bin_dir:${installerPath}"

    version_args=""
    [ "$want" = latest ] || version_args="--version $want"

    curl -fsSL ${installerUrl} \
      | bash -s -- --install-dir "$bin_dir" --force $version_args

    mkdir -p "$(dirname "$state")"
    printf '%s\n' "$want" > "$state"
  '';
in
{
  options.wolfie = {
    enable = lib.mkEnableOption "wolfie, installed with its curl bootstrap script";
    version = lib.mkOption {
      type = lib.types.str;
      default = "latest";
      example = "v0.9.20b";
      description = "Release tag passed to install.sh --version, or \"latest\".";
    };
  };

  config = lib.mkIf cfg.enable {
    programs.nix-ld.enable = true;

    home-manager.users.${username} = { lib, ... }: {
      systemd.user.services.wolfie-install = {
        Unit = {
          Description = "Install wolfie via its bootstrap script";
          # Keep retrying until the network is up; never give up.
          StartLimitIntervalSec = 0;
        };
        Service = {
          Type = "oneshot";
          ExecStart = "${install-wolfie}";
          Restart = "on-failure";
          RestartSec = 60;
        };
        Install.WantedBy = [ "default.target" ];
      };

      # Config from the Arch box, seeded once and then left editable. The
      # theme file is normally regenerated by wallust (colors-wolfie.json
      # template); the seed means `"theme": "wallust-plasma"` resolves before
      # wallust has run.
      home.activation.seedWolfieConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        if [ ! -e "$HOME/.config/wolfie/config.json" ]; then
          run install -Dm644 ${../assets/wolfie/config.json} "$HOME/.config/wolfie/config.json"
        fi
        if [ ! -e "$HOME/.config/wolfie/themes/wallust-plasma.json" ]; then
          run install -Dm644 ${../assets/wolfie/wallust-plasma.json} "$HOME/.config/wolfie/themes/wallust-plasma.json"
        fi
      '';
    };
  };
}
