# Hyprland, translated from ~/.config/hypr/hyprland.conf on the Arch box.
# nixpkgs ships hyprland 0.56.2 — the exact version you were running — so the
# newer block-style `windowrule { ... }` syntax below is supported as written.
#
# Deliberately NOT managed here (they are written at runtime by other tools;
# a read-only /nix/store symlink would break them):
#   ~/.config/hypr/monitors.conf    <- generated by nwg-displays
#   ~/.cache/wallust/hyprland.conf  <- generated by wallust on wallpaper change
# Both are `source`d instead, so they stay ordinary mutable files. dotfiles.nix
# seeds them on first activation so Hyprland starts without config errors.
{ pkgs, ... }:
{
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    # MUST be set explicitly. home-manager's default for this option flips to
    # "lua" at home.stateVersion >= 26.05, and the Lua backend cannot express
    # hyprlang `$variables` — it emits `hl.$terminal("ghostty")`, which is not
    # valid Lua. Your config is hyprlang, so pin it.
    configType = "hyprlang";
    # Puts the `source` lines before everything else, so the wallust colour
    # variables ($active_border_color etc.) are defined before general{} uses
    # them. This is the default, stated here because the config depends on it.
    sourceFirst = true;

    settings = {
      source = [
        "~/.config/hypr/monitors.conf"
        "~/.cache/wallust/hyprland.conf"
      ];

      # Fallback for any output without a rule in monitors.conf.
      monitor = ",preferred,auto,auto";

      "$terminal" = "ghostty";
      "$fileManager" = "dolphin";
      "$menu" = "rofi -show drun -config ~/.config/rofi/config.rasi";
      "$mainMod" = "SUPER";

      env = [
        "XDG_CURRENT_DESKTOP,Hyprland"
        "XDG_SESSION_DESKTOP,Hyprland"
        "XDG_SESSION_TYPE,wayland"
        "XCURSOR_SIZE,18"
        "HYPRCURSOR_SIZE,18"
      ];

      exec-once = [
        # Export the Wayland session to D-Bus/systemd first.
        "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE"
        # KDE wallet-backed helpers (you run KDE apps under Hyprland).
        "systemctl --user start plasma-kwallet-pam.service plasma-kded6.service"
        "qdbus6 org.kde.kwalletd6 /modules/kwalletd6 org.kde.KWallet.open kdewallet 0 login"
        "ksecretd"
        # On NixOS the polkit agent is a store path, not /usr/lib — reference
        # the package so it resolves wherever Nix put it.
        "${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1"
        "nm-applet --indicator"
        "${pkgs.swaynotificationcenter}/bin/swaync"
        "waybar & hyprpaper & firefox"
        "wl-paste --type text --watch cliphist store"
        "wl-paste --type image --watch cliphist store"
      ];

      general = {
        gaps_in = 3;
        gaps_out = 10;
        border_size = 2;
        "col.active_border" = "$active_border_color";
        "col.inactive_border" = "$inactive_border_color";
        resize_on_border = false;
        allow_tearing = false;
        layout = "dwindle";
      };

      decoration = {
        rounding = 15;
        active_opacity = 0.75;
        inactive_opacity = 0.75;
        blur = {
          enabled = true;
          size = 6;
          passes = 2;
          vibrancy = 0.1696;
        };
      };

      animations = {
        enabled = true;
        bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
        animation = [
          "windows, 1, 7, myBezier"
          "windowsOut, 1, 7, default, popin 80%"
          "border, 1, 10, default"
          "borderangle, 1, 8, default"
          "fade, 1, 7, default"
          "workspaces, 1, 6, default"
        ];
      };

      dwindle.preserve_split = true;
      master.new_status = "master";

      misc = {
        force_default_wallpaper = 0;
        disable_hyprland_logo = false;
      };

      input = {
        kb_layout = "us";
        follow_mouse = 0;
        sensitivity = 0;
        touchpad.natural_scroll = false;
      };

      device = {
        name = "epic-mouse-v1";
        sensitivity = -0.5;
      };

      bind = [
        # --- core ---
        "$mainMod, T, exec, $terminal"
        "$mainMod, C, killactive,"
        "$mainMod, Q, killactive,"
        "$mainMod, M, exit,"
        "$mainMod, E, exec, $fileManager"
        "$mainMod, V, exec, ~/.config/hypr/scripts/ClipManager.sh"
        "$mainMod, R, exec, $menu"
        "ALT, Space, exec, $menu"
        "$mainMod, P, pseudo,"
        "$mainMod, backslash, layoutmsg, togglesplit,"

        # --- focus by arrows ---
        "$mainMod, left, movefocus, l"
        "$mainMod, right, movefocus, r"
        "$mainMod, up, movefocus, u"
        "$mainMod, down, movefocus, d"

        # --- workspaces ---
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
        "$mainMod, 0, workspace, 10"
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"
        "$mainMod, S, togglespecialworkspace, magic"
        "$mainMod SHIFT, G, movetoworkspace, special:magic"

        "$mainMod SHIFT, S, exec, spectacle -r -b -c -n"
        "$mainMod, mouse_down, workspace, e+1"
        "$mainMod, mouse_up, workspace, e-1"

        # --- app launchers (carried over from the Plasma shortcuts) ---
        "CTRL ALT, T, exec, ghostty"
        "CTRL ALT, B, exec, zen-browser"
        "CTRL ALT, C, exec, zed"
        "CTRL ALT, O, exec, obsidian"
        "CTRL SHIFT, Escape, exec, plasma-systemmonitor"
        "$mainMod, Escape, exec, plasma-systemmonitor"

        # --- vim-style focus (was Krohnkite Meta+HJKL) ---
        "$mainMod, H, movefocus, l"
        "$mainMod, J, movefocus, d"
        "$mainMod, K, movefocus, u"
        "$mainMod, L, exec, ~/.config/hypr/scripts/LockScreen.sh"
        "$mainMod SHIFT, Escape, exec, ~/.config/hypr/scripts/Wlogout.sh"
        "$mainMod, N, exec, ${pkgs.swaynotificationcenter}/bin/swaync-client -t -sw"

        # --- vim-style window movement ---
        "$mainMod SHIFT, H, movewindow, l"
        "$mainMod SHIFT, J, movewindow, d"
        "$mainMod SHIFT, K, movewindow, u"
        "$mainMod SHIFT, L, movewindow, r"

        # --- window management ---
        "ALT, F4, killactive,"
        "$mainMod, F, togglefloating,"
        "$mainMod, Prior, fullscreen, 1"
        "$mainMod, Next, movetoworkspacesilent, special:minimized"
        "$mainMod, Backspace, fullscreen, 0"
        "ALT, Tab, cyclenext,"
        "ALT SHIFT, Tab, cyclenext, prev"

        # --- workspace / monitor ---
        "$mainMod CTRL, right, workspace, e+1"
        "$mainMod CTRL, left, workspace, e-1"
        "$mainMod SHIFT, right, movewindow, mon:+1"
        "$mainMod SHIFT, left, movewindow, mon:-1"
      ];

      # Repeating binds (held down).
      binde = [
        "$mainMod CTRL, H, resizeactive, -40 0"
        "$mainMod CTRL, J, resizeactive, 0 40"
        "$mainMod CTRL, K, resizeactive, 0 -40"
        "$mainMod CTRL, L, resizeactive, 40 0"
      ];

      # Locked binds (work while the screen is locked).
      bindl = [
        ", XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
        ", XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
        "SHIFT, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+"
        "SHIFT, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"
        ", XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
        ", XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
        "$mainMod, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
        ", XF86AudioPlay, exec, playerctl play-pause"
        ", XF86AudioPause, exec, playerctl play-pause"
        ", XF86AudioNext, exec, playerctl next"
        ", XF86AudioPrev, exec, playerctl previous"
        ", XF86AudioStop, exec, playerctl stop"
        ", XF86MonBrightnessUp, exec, brightnessctl set +10%"
        ", XF86MonBrightnessDown, exec, brightnessctl set 10%-"
        "SHIFT, XF86MonBrightnessUp, exec, brightnessctl set +1%"
        "SHIFT, XF86MonBrightnessDown, exec, brightnessctl set 1%-"
        ", XF86KbdBrightnessUp, exec, brightnessctl -d *::kbd set +10%"
        ", XF86KbdBrightnessDown, exec, brightnessctl -d *::kbd set 10%-"
      ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];

      # Repeated blocks are expressed as a list of attrsets.
      windowrule = [
        {
          name = "Youtube";
          "match:title" = ".*- YouTube.*";
          opacity = "1.0 override 1.0 override";
        }
        # NOTE: the second Youtube rule on Arch was
        #     match:title = .*| Watch |.*
        # As a regex that is the alternation  (.*) | ( Watch ) | (.*)  — the
        # first branch matches ANY title, so it forced opacity 1.0 on every
        # window and quietly cancelled your 0.75 global transparency.
        # Fixed to actually mean "contains | Watch |":
        {
          name = "Youtube-Watch";
          "match:title" = ".*\\| Watch \\|.*";
          opacity = "1.0 override 1.0 override";
        }
        {
          name = "PnP";
          "match:title" = "Picture-in-Picture";
        }
        {
          name = "Floating Windows";
          "match:class" = "^(zoom|RocketChat)$";
          float = true;
        }
      ];
    };
  };

  # hyprpaper. The wallpaper is shipped in the flake so it exists on any box.
  services.hyprpaper = {
    enable = true;
    settings = {
      preload = [ "${./assets/wallpapers/a_group_of_flowers_in_a_vase.jpg}" ];
      wallpaper = [ ",${./assets/wallpapers/a_group_of_flowers_in_a_vase.jpg}" ];
    };
  };

  # The four helper scripts your binds call. Kept as real executable files.
  home.file = {
    ".config/hypr/scripts/ClipManager.sh" = { source = ./assets/hypr-scripts/ClipManager.sh; executable = true; };
    ".config/hypr/scripts/LockScreen.sh" = { source = ./assets/hypr-scripts/LockScreen.sh; executable = true; };
    ".config/hypr/scripts/Wlogout.sh" = { source = ./assets/hypr-scripts/Wlogout.sh; executable = true; };
    ".config/hypr/scripts/AirplaneMode.sh" = { source = ./assets/hypr-scripts/AirplaneMode.sh; executable = true; };
  };
}
